//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatcHWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AAB_BANKEntities : DbContext
    {
        public AAB_BANKEntities()
            : base("name=AAB_BANKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Wave_Plan> Wave_Plan { get; set; }
    
        public virtual ObjectResult<spGET_IT_PRODUCT_ALL_Result> spGET_IT_PRODUCT_ALL(string lMAI, string lOAR_id, string lIT_PRODUCT, Nullable<decimal> lIT_PRODUCT_ID, Nullable<decimal> lCIA_RATING, string lDOMAIN, string lWP_4)
        {
            var lMAIParameter = lMAI != null ?
                new ObjectParameter("lMAI", lMAI) :
                new ObjectParameter("lMAI", typeof(string));
    
            var lOAR_idParameter = lOAR_id != null ?
                new ObjectParameter("lOAR_id", lOAR_id) :
                new ObjectParameter("lOAR_id", typeof(string));
    
            var lIT_PRODUCTParameter = lIT_PRODUCT != null ?
                new ObjectParameter("lIT_PRODUCT", lIT_PRODUCT) :
                new ObjectParameter("lIT_PRODUCT", typeof(string));
    
            var lIT_PRODUCT_IDParameter = lIT_PRODUCT_ID.HasValue ?
                new ObjectParameter("lIT_PRODUCT_ID", lIT_PRODUCT_ID) :
                new ObjectParameter("lIT_PRODUCT_ID", typeof(decimal));
    
            var lCIA_RATINGParameter = lCIA_RATING.HasValue ?
                new ObjectParameter("lCIA_RATING", lCIA_RATING) :
                new ObjectParameter("lCIA_RATING", typeof(decimal));
    
            var lDOMAINParameter = lDOMAIN != null ?
                new ObjectParameter("lDOMAIN", lDOMAIN) :
                new ObjectParameter("lDOMAIN", typeof(string));
    
            var lWP_4Parameter = lWP_4 != null ?
                new ObjectParameter("lWP_4", lWP_4) :
                new ObjectParameter("lWP_4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGET_IT_PRODUCT_ALL_Result>("spGET_IT_PRODUCT_ALL", lMAIParameter, lOAR_idParameter, lIT_PRODUCTParameter, lIT_PRODUCT_IDParameter, lCIA_RATINGParameter, lDOMAINParameter, lWP_4Parameter);
        }
    
        public virtual int fnGET_IT_PRODUCT_ALL(string lMAI, string lOAR_id, string lIT_PRODUCT, Nullable<decimal> lIT_PRODUCT_ID, Nullable<decimal> lCIA_RATING, string lDOMAIN, string lWP_4)
        {
            var lMAIParameter = lMAI != null ?
                new ObjectParameter("lMAI", lMAI) :
                new ObjectParameter("lMAI", typeof(string));
    
            var lOAR_idParameter = lOAR_id != null ?
                new ObjectParameter("lOAR_id", lOAR_id) :
                new ObjectParameter("lOAR_id", typeof(string));
    
            var lIT_PRODUCTParameter = lIT_PRODUCT != null ?
                new ObjectParameter("lIT_PRODUCT", lIT_PRODUCT) :
                new ObjectParameter("lIT_PRODUCT", typeof(string));
    
            var lIT_PRODUCT_IDParameter = lIT_PRODUCT_ID.HasValue ?
                new ObjectParameter("lIT_PRODUCT_ID", lIT_PRODUCT_ID) :
                new ObjectParameter("lIT_PRODUCT_ID", typeof(decimal));
    
            var lCIA_RATINGParameter = lCIA_RATING.HasValue ?
                new ObjectParameter("lCIA_RATING", lCIA_RATING) :
                new ObjectParameter("lCIA_RATING", typeof(decimal));
    
            var lDOMAINParameter = lDOMAIN != null ?
                new ObjectParameter("lDOMAIN", lDOMAIN) :
                new ObjectParameter("lDOMAIN", typeof(string));
    
            var lWP_4Parameter = lWP_4 != null ?
                new ObjectParameter("lWP_4", lWP_4) :
                new ObjectParameter("lWP_4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fnGET_IT_PRODUCT_ALL", lMAIParameter, lOAR_idParameter, lIT_PRODUCTParameter, lIT_PRODUCT_IDParameter, lCIA_RATINGParameter, lDOMAINParameter, lWP_4Parameter);
        }
    }
}
